[tool.poetry]
name = "yirimirai"
version = "0.1.0"
description = ""
authors = ["忘忧北萱草 <wybxc@qq.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Quart = "^0.15.1"
httpx = "^0.18.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
